Update limpiar.yml

diff --git a/.github/workflows/limpiar.yml b/.github/workflows/limpiar.yml
--- a/.github/workflows/limpiar.yml
+++ b/.github/workflows/limpiar.yml
@@ -1,60 +1,24 @@
-name: Crear y Limpiar Nuevo Repositorio
+name: Create New Repo Dispatch
 
 on:
-  repository_dispatch:
+  workflow_run:
+    workflows: ["Limpiar carpetas y archivos innecesarios"]
     types:
-      - create-new-repo
+      - completed
 
 jobs:
-  limpiar:
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
-
-    - name: Set up Git
-      env:
-        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Usar el token de acceso personal
-      run: |
-        git config user.name "GitHub Actions"
-        git config user.email "actions@github.com"
-
-    - name: Limpiar archivos y carpetas
-      run: |
-        rm -rf .github/ISSUE_TEMPLATE
-        rm -rf ejemplos
-        rm -rf trabajos_de_estudiantes
-        rm -rf modulos
-        rm CONTRIBUTING.md
-        find . -type f ! -name 'INSTRUCCIONES.md' -delete
-        find . -type d -empty -delete
-
-    - name: Commit changes
-      run: |
-        git add .
-        git diff --quiet --exit-code || git commit -m "Limpiar carpetas y archivos innecesarios"
-        
-    - name: Push changes
-      run: |
-        git push origin main
-
   build:
-    needs: limpiar
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout Repo
-      uses: actions/checkout@v2
+    - name: Check if previous job succeeded
+      run: |
+        if [ ${{ job.status }} != "success" ]; then
+          echo "Previous job failed"
+          exit 1
+        fi
 
-    - name: Crea un Nuevo Repositorio
-      uses: repo-sync/github-repo-create@v2
-      env:
-        REPO_NAME: "Nuevo-Repositorio"
-        REPO_PRIVATE: "false"
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-    - name: Crear un Despacho Personalizado
+    - name: Create Dispatch
       run: |
         echo "{\"event_type\": \"create-new-repo\"}" > event.json
         curl -X POST \
@@ -62,3 +26,4 @@ jobs:
           -H "Accept: application/vnd.github.everest-preview+json" \
           -d @event.json \
           https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches
+
